# This is a basic workflow that is manually triggered

name: 2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Build Type'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - sky
        - staging
        - debug
      flavor:
        description: 'Build Flavor'
        required: true
        default: 'midroid'
        type: choice
        options:
        - android
        - midroid
        - indusos
        - oppo
        - huawei
        - samsung
        - vivo
        - lgstore

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: build with type and flavour
      run: echo "Building with ${{ github.event.inputs.type }} ${{ github.event.inputs.flavour }}"
