# This is a basic workflow that is manually triggered
name: 2

on:
  # Trigger for manual apk generation

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Build Type'
        required: true
        default: 'release'
        type: choice
        options:
        - release
        - sky
        - staging
        - debug
        - vapt
        - all
      flavor:
        description: 'Build Flavor'
        required: true
        default: 'android'
        type: choice
        options:
        - android
        - midroid
        - indusos
        - oppo
        - huawei
        - samsung
        - vivo
        - lgstore

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: build with type and flavour
      run: echo "Building with ${{ github.event.inputs.name }} ${{ github.event.inputs.flavor }}"

  build_release_midroid:
    # wait until project is build successfully

    runs-on: ubuntu-latest

    steps:
    
      #1.
      - name: Checkout
        uses: actions/checkout@v2.4.0
        
      #2.
      - name: Setup Java JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      #3. Setup Runtime Permission for gradle in Linux OS
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      #4. Clean Project
      - name: Build Clean
        run: ./gradlew clean
